doc-warnings: yes
test-warnings: no
strictness: veryhigh
max-line-length: 120
uses:
    - django
autodetect: yes
requirements:
    - requirements.txt
ignore-paths:
    - docs
pylint:
  disable:
    - super-on-old-class
    - old-style-class
    - no-init
    - nonstandard-exception
    - too-few-public-methods
