language: python
python:
- '2.7'
- '3.4'
install:
- pip install -U pip
- pip install -r requirements-frozen.txt
branches:
  only:
  - master
before_script:
- psql -c "CREATE USER moneypot WITH PASSWORD '"$PG_PASSWORD"';" -U postgres
- psql -c "ALTER USER moneypot WITH SUPERUSER;" -U postgres
- psql -c "CREATE DATABASE moneypot_dist;" -U postgres
- psql -c "GRANT ALL PRIVILEGES ON DATABASE moneypot_dist to moneypot;" -U postgres
- cp moneypot/settings/local-dist.py moneypot/settings/local.py
- python manage.py syncdb --noinput
- python manage.py migrate --noinput
script:
- coverage run --source='base' --omit='*migrations*' manage.py test
after_success:
- coveralls
addons:
  postgresql: '9.3'
  code_climate:
    repo_token:
      secure: G55bZ4aEUhyCIZ4IeYokTVL47rbkltLdjA93ch3woHpZ3FV7EWuBlYFTNWIvyJgePhuO4I1sNk2HxyRb/RoIH65hHeqNADISDt8U+efjpS55oTV7xcmfDAASwPVuC36a0tJejDLt7cdTUka9eZXDso4VT7I711jUKLu7FGTmDWI=
notifications:
  email:
    recipients:
    - shamanu4+travis.moneypot-api@gmail.com
  hipchat:
    rooms:
      secure: gcl4HuGdwFG0rxEMtjEEThW2GJNWS5pB5mSWNO3o8UaAcOTj8hnmknJcGIFSZ0C4gtvtbacxVkSZwy1HtUroKGSMLba+BpHQv0Ccq6OC/+B7UxF+UCkcyQkvhZoQe43BG3CG3v3fp41lDXLZX19It7Kye5cGoLAh8Zl9qbO9fEc=
    on_success: always
    on_failure: always
    notify: true
env:
  global:
  - secure: h1F90gXcLzDzTLj/dhXUARYdsl0CsPrRdFWn4Ur+O1LDMczg0M588FNrSmyj5yq0cbvxJNbCUxS9bXt6BY81FCFSOqXb4YapxWpCa0FZQ2bDTs/hfJu5QZOW3+RahFeHBCP/EQfPbo+NYHujHGgoMNdetZmTFmfzsrLPx8/lwKQ=
  - secure: oBcJ4Es4wu0S1NNkXAmfRehoTSKEfVP3DAer/n9LC0YkWNJ6g5LX1IPm64+WJ7VjN74d08LmgjUPHQJhLmor7RwpCKJrGQ2Ty8rkgV7IR2fOVSr1p3RmeZPxjmjE9x9Is3q3KIXXTxh0r0xffscC9W2jSUv/KvSVVCEwBBUlqOA=
dd:
  secure: mjFe8oWtvqF774wAovXshV78Fjr3wY994G0UNDZwQX/gD+oz0JNfOe4WtJJBsho2nKRBlg7efuAO8B3WZNf1SMA4jkpXOHQjOqOb1DjlS7tD96zND3eLBaRuunzaCcYz37/GFVvU1XZfKAZdSmFiG+83YxfBsVE7Q6hlHZRWRcY=
