language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"

install:
  - "pip install -U pip"
  - "pip install -r requirements-frozen.txt"

branches:
  only:
    - master

before_script:
  - "python manage.py syncdb --noinput"
  - "python manage.py migrate --noinput"

script:
  - "python manage.py test"

addons:
  code_climate:
    repo_token:
      secure: "G55bZ4aEUhyCIZ4IeYokTVL47rbkltLdjA93ch3woHpZ3FV7EWuBlYFTNWIvyJgePhuO4I1sNk2HxyRb/RoIH65hHeqNADISDt8U+efjpS55oTV7xcmfDAASwPVuC36a0tJejDLt7cdTUka9eZXDso4VT7I711jUKLu7FGTmDWI="

notifications:
  email:
    recipients:
      - shamanu4+travis.moneypot-api@gmail.com